### ISSUE TITLE
reg pdb_contact.py

### ISSUE THREAD

**Issue by rraadd88** [harmslab/pdbtools#1]
Hi, I am not sure about the unit of the distance cut off. My proteins average width is ~90 A  which is equivalent to ~1000 cut off. Is it some arbitrary unit?

**Comment by Zsailer** [comment]
@rraadd88 The units for cutoff distance is meant to be in angstroms.

However, I believe there is a mistake in the code as it is currently written. It's comparing the cutoff distance to the _squared_ distance between target and residue. In other words, the units don't line up.

I'll submit a fix.

In the meantime, you can just square the cutoff distance you want to use (in units of angstroms), and it should work the way your expect.

**Comment by Zsailer** [comment]
@rraadd88 should work now. 

If you're still having a problem, let us know! Closing this issue.
